# Generated by Django 4.2.2 on 2023-06-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_bio_alter_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
    ]
