# Generated by Django 4.2.2 on 2023-06-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_passwordrestore_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordRestore',
        ),
    ]
