# Generated by Django 4.2.2 on 2023-06-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tagList',
            field=models.ManyToManyField(blank=True, to='posts.tag'),
        ),
    ]
