# Generated by Django 4.2.2 on 2023-06-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_comments_post_dislikes_post_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postImage',
            field=models.ImageField(default='empty_body.jpg', null=True, upload_to=''),
        ),
    ]
