# Generated by Django 4.2.2 on 2023-06-11 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_post_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='addedToFav',
            field=models.ManyToManyField(blank=True, related_name='addedToFav', to=settings.AUTH_USER_MODEL),
        ),
    ]
