# Generated by Django 4.2.2 on 2023-06-12 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_addedtofav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
